<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType Condition="'$(FrinkyExport)' != 'true'">Exe</OutputType>
    <OutputType Condition="'$(FrinkyExport)' == 'true'">WinExe</OutputType>
    <RootNamespace>FrinkyEngine.Runtime</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FrinkyEngine.Core\FrinkyEngine.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\Shaders\**\*" CopyToOutputDirectory="PreserveNewest" LinkBase="Shaders" />
    <Content Include="..\..\EngineContent\**\*" CopyToOutputDirectory="PreserveNewest" LinkBase="EngineContent" Condition="Exists('..\..\EngineContent')" />
  </ItemGroup>

</Project>
